#pragma once

#define PROPERTIES_ENGINE_START 6

typedef enum {
	TYPE_INT, TYPE_FLOAT
} TYPE;

typedef struct {
	char name[0xFF];
	int offset;
	TYPE type;
} PROPERTY;

static PROPERTY visual_properties[] = {
	{ "DOF Intensity", 0x70, TYPE_FLOAT },
	{ "DOF Feather", 0x64, TYPE_FLOAT },
	{ "DOF Samples", 0x68, TYPE_FLOAT },
	{ "DOF Focus", 0x8C, TYPE_FLOAT },
	{ "DOF Creep", 0x84, TYPE_FLOAT },
	{ "DOF Glow", 0xA0, TYPE_FLOAT },
	{ "Saturation", 0x258, TYPE_FLOAT },
	{ "Blue Tint", 0x25C, TYPE_FLOAT },
	{ "Pink Tint", 0x260, TYPE_FLOAT },
	{ "Yellow Tint", 0x264, TYPE_FLOAT },
	{ "Blue Tint", 0x268, TYPE_FLOAT },
	{ "Pink Tint", 0x26C, TYPE_FLOAT },
	{ "Yellow Tint", 0x270, TYPE_FLOAT },
	{ "Red Tint", 0x274, TYPE_FLOAT },
	{ "Green Tint", 0x278, TYPE_FLOAT },
	{ "Blue Tint", 0x27C, TYPE_FLOAT },
	{ "Sun Red Tint", 0x284, TYPE_FLOAT },
	{ "Sun Green Tint", 0x288, TYPE_FLOAT },
	{ "Sun Blue Tint", 0x28C, TYPE_FLOAT },
	{ "Sun Floor Glow Threshold", 0x290, TYPE_FLOAT },
	{ "Sun Glow Radius", 0x294, TYPE_FLOAT },
	{ "Sun Glow Threshold", 0x298, TYPE_FLOAT },
	{ "Sun Sky Glow Threshold", 0x29C, TYPE_FLOAT },
	{ "Sun World Glow Threshold", 0x2A0, TYPE_FLOAT },
	{ "Contrast", 0x2A8, TYPE_FLOAT },
	{ "Sun Glow", 0x2B0, TYPE_FLOAT },
	{ "Screen Bleach", 0x2B4, TYPE_FLOAT },
	{ "Sun Glow Toggle", 0x2B8, TYPE_INT },
	{ "Glow Position X", 0x2BC, TYPE_FLOAT },
	{ "Glow Position Y", 0x2C0, TYPE_FLOAT },
	{ "Glow Position Z", 0x2C4, TYPE_FLOAT },
	{ "Brightness", 0x2C8, TYPE_FLOAT },
	{ "Brightness Threshold", 0x2D4, TYPE_FLOAT },
	{ "World Brightness", 0x2D8, TYPE_FLOAT },
	{ "Red Threshold", 0x310, TYPE_FLOAT },
	{ "Green Threshold", 0x314, TYPE_FLOAT },
	{ "Blue Threshold", 0x318, TYPE_FLOAT },
	{ "Red Threshold", 0x31C, TYPE_FLOAT },
	{ "Green Threshold", 0x320, TYPE_FLOAT },
	{ "Blue Threshold", 0x324, TYPE_FLOAT },
	{ "Red Threshold", 0x328, TYPE_FLOAT },
	{ "Blue Threshold", 0x32C, TYPE_FLOAT },
	{ "Green Threshold", 0x330, TYPE_FLOAT },
	{ "Red Threshold", 0x334, TYPE_FLOAT },
	{ "Green Threshold", 0x338, TYPE_FLOAT },
	{ "Blue Threshold", 0x33C, TYPE_FLOAT },
	{ "Red Threshold", 0x340, TYPE_FLOAT },
	{ "Green Threshold", 0x344, TYPE_FLOAT },
	{ "Blue Threshold", 0x348, TYPE_FLOAT },
	{ "Red Threshold", 0x34C, TYPE_FLOAT },
	{ "Green Threshold", 0x350, TYPE_FLOAT },
	{ "Blue Threshold", 0x354, TYPE_FLOAT },
	{ "Red Threshold", 0x358, TYPE_FLOAT },
	{ "Green Threshold", 0x35C, TYPE_FLOAT },
	{ "Blue Threshold", 0x360, TYPE_FLOAT },
	{ "Red Threshold", 0x364, TYPE_FLOAT },
	{ "Green Threshold", 0x368, TYPE_FLOAT },
	{ "Blue Threshold", 0x36C, TYPE_FLOAT },
	{ "Red Threshold", 0x370, TYPE_FLOAT },
	{ "Green Threshold", 0x374, TYPE_FLOAT },
	{ "Blue Threshold", 0x378, TYPE_FLOAT },
	{ "Red Threshold", 0x37C, TYPE_FLOAT },
	{ "Green Threshold", 0x380, TYPE_FLOAT },
	{ "Blue Threshold", 0x384, TYPE_FLOAT },
	{ "Red Threshold", 0x388, TYPE_FLOAT },
	{ "Green Threshold", 0x38C, TYPE_FLOAT },
	{ "Blue Threshold", 0x390, TYPE_FLOAT },
	{ "Red Threshold", 0x394, TYPE_FLOAT },
	{ "Green Threshold", 0x398, TYPE_FLOAT },
	{ "Blue Threshold", 0x39C, TYPE_FLOAT },
	{ "Red Threshold", 0x3A0, TYPE_FLOAT },
	{ "Green Threshold", 0x3A4, TYPE_FLOAT },
	{ "Blue Threshold", 0x3A8, TYPE_FLOAT },
	{ "Red Threshold", 0x3AC, TYPE_FLOAT },
	{ "Green Threshold", 0x3B0, TYPE_FLOAT },
	{ "Blue Threshold", 0x3B4, TYPE_FLOAT },
	{ "Red Tint", 0x3C4, TYPE_FLOAT },
	{ "Green Tint", 0x3C8, TYPE_FLOAT },
	{ "Blue Tint", 0x3CC, TYPE_FLOAT },
	{ "Red Threshold", 0x3D0, TYPE_FLOAT },
	{ "Green Threshold", 0x3D4, TYPE_FLOAT },
	{ "Blue Threshold", 0x3D8, TYPE_FLOAT },
	{ "Red Threshold", 0x3DC, TYPE_FLOAT },
	{ "Green Threshold", 0x3E0, TYPE_FLOAT },
	{ "Blue Threshold", 0x3E4, TYPE_FLOAT },
	{ "Red Threshold", 0x3E8, TYPE_FLOAT },
	{ "Green Threshold", 0x3EC, TYPE_FLOAT },
	{ "Blue Threshold", 0x3F0, TYPE_FLOAT },
	{ "Red Threshold", 0x3F4, TYPE_FLOAT },
	{ "Green Threshold", 0x3F8, TYPE_FLOAT },
	{ "Blue Threshold", 0x3FC, TYPE_FLOAT },
	{ "Red Threshold", 0x400, TYPE_FLOAT },
	{ "Green Threshold", 0x404, TYPE_FLOAT },
	{ "Blue Threshold", 0x408, TYPE_FLOAT },
	{ "Red Threshold", 0x40C, TYPE_FLOAT },
	{ "Green Threshold", 0x410, TYPE_FLOAT },
	{ "Blue Threshold", 0x414, TYPE_FLOAT },
	{ "Red Threshold", 0x418, TYPE_FLOAT },
	{ "Green Threshold", 0x41C, TYPE_FLOAT },
	{ "Blue Threshold", 0x420, TYPE_FLOAT },
	{ "Red Threshold", 0x424, TYPE_FLOAT },
	{ "Green Threshold", 0x428, TYPE_FLOAT },
	{ "Blue Threshold", 0x42C, TYPE_FLOAT },
	{ "Red Threshold", 0x430, TYPE_FLOAT },
	{ "Green Threshold", 0x434, TYPE_FLOAT },
	{ "Blue Threshold", 0x438, TYPE_FLOAT },
	{ "Red Threshold", 0x43C, TYPE_FLOAT },
	{ "Green Threshold", 0x440, TYPE_FLOAT },
	{ "Blue Threshold", 0x444, TYPE_FLOAT },
	{ "Red Threshold", 0x448, TYPE_FLOAT },
	{ "Green Threshold", 0x44C, TYPE_FLOAT },
	{ "Blue Threshold", 0x450, TYPE_FLOAT },
	{ "Red Threshold", 0x454, TYPE_FLOAT },
	{ "Green Threshold", 0x458, TYPE_FLOAT },
	{ "Blue Threshold", 0x45C, TYPE_FLOAT },
	{ "Red Threshold", 0x460, TYPE_FLOAT },
	{ "Green Threshold", 0x464, TYPE_FLOAT },
	{ "Blue Threshold", 0x468, TYPE_FLOAT },
	{ "Red Threshold", 0x46C, TYPE_FLOAT },
	{ "Green Threshold", 0x470, TYPE_FLOAT },
	{ "Blue Threshold", 0x474, TYPE_FLOAT },
	{ "Skybox Threshold", 0xA94, TYPE_FLOAT },
	{ "Saturation", 0x9A0, TYPE_FLOAT },
	{ "Blue Tint", 0x9A4, TYPE_FLOAT },
	{ "Purple Tint", 0x9A8, TYPE_FLOAT },
	{ "Yellow Tint", 0x9AC, TYPE_FLOAT },
	{ "Blue Tint", 0x9B0, TYPE_FLOAT },
	{ "Purple Tint", 0x9B4, TYPE_FLOAT },
	{ "Yellow Tint", 0x9B8, TYPE_FLOAT },
	{ "Red Tint", 0x9BC, TYPE_FLOAT },
	{ "Green Tint", 0x9C0, TYPE_FLOAT },
	{ "Blue Tint", 0x9C4, TYPE_FLOAT },
	{ "Sun Red Glow", 0x9C8, TYPE_FLOAT },
	{ "Sun Green Glow", 0x9CC, TYPE_FLOAT },
	{ "Sun Blue Glow", 0x9D0, TYPE_FLOAT },
	{ "Sun Glow Threshold", 0x9D4, TYPE_FLOAT },
	{ "Sun Glow Radius", 0x9D8, TYPE_FLOAT },
	{ "Sun Floor Glow Radius", 0x9DC, TYPE_FLOAT },
	{ "Sun Outer Radius", 0x9E0, TYPE_FLOAT },
	{ "Sun Glow etc", 0x9E4, TYPE_FLOAT },
	{ "Sun Glow Intensity", 0x9F4, TYPE_FLOAT },
	{ "Screen Bleach", 0x9F8, TYPE_FLOAT },
	{ "World Glow", 0x9FC, TYPE_FLOAT },
	{ "World Glow", 0xA0C, TYPE_FLOAT },
	{ "Red Threshold", 0xA18, TYPE_FLOAT },
	{ "Green Threshold", 0xA1C, TYPE_FLOAT },
	{ "Blue Threshold", 0xA20, TYPE_FLOAT },
	{ "Red Threshold", 0xA24, TYPE_FLOAT },
	{ "Green Threshold", 0xA28, TYPE_FLOAT },
	{ "Blue Threshold", 0xA2C, TYPE_FLOAT },
	{ "Red Threshold", 0xA30, TYPE_FLOAT },
	{ "Green Threshold", 0xA34, TYPE_FLOAT },
	{ "Blue Threshold", 0xA38, TYPE_FLOAT },
	{ "Red Threshold", 0xA3C, TYPE_FLOAT },
	{ "Green Threshold", 0xA40, TYPE_FLOAT },
	{ "Blue Threshold", 0xA44, TYPE_FLOAT },
	{ "Red Threshold", 0xA48, TYPE_FLOAT },
	{ "Green Threshold", 0xA4C, TYPE_FLOAT },
	{ "Blue Threshold", 0xA50, TYPE_FLOAT },
	{ "Red Threshold", 0xA54, TYPE_FLOAT },
	{ "Green Threshold", 0xA58, TYPE_FLOAT },
	{ "Blue Threshold", 0xA5C, TYPE_FLOAT },
	{ "Red Threshold", 0xA60, TYPE_FLOAT },
	{ "Green Threshold", 0xA64, TYPE_FLOAT },
	{ "Blue Threshold", 0xA68, TYPE_FLOAT },
	{ "Red Threshold", 0xA6C, TYPE_FLOAT },
	{ "Green Threshold", 0xA70, TYPE_FLOAT },
	{ "Blue Threshold", 0xA74, TYPE_FLOAT },
	{ "Red Threshold", 0xA78, TYPE_FLOAT },
	{ "Green Threshold", 0xA7C, TYPE_FLOAT },
	{ "Blue Threshold", 0xA80, TYPE_FLOAT },
	{ "Red Threshold", 0xA84, TYPE_FLOAT },
	{ "Green Threshold", 0xA88, TYPE_FLOAT },
	{ "Blue Threshold", 0xA8C, TYPE_FLOAT },
	{ "Red Threshold", 0xA90, TYPE_FLOAT },
	{ "Green Threshold", 0xA94, TYPE_FLOAT },
	{ "Blue Threshold", 0xA98, TYPE_FLOAT },
	{ "Red Threshold", 0xA9C, TYPE_FLOAT },
	{ "Green Threshold", 0xAA0, TYPE_FLOAT },
	{ "Blue Threshold", 0xAA4, TYPE_FLOAT },
	{ "Red Threshold", 0xAA8, TYPE_FLOAT },
	{ "Green Threshold", 0xAAC, TYPE_FLOAT },
	{ "Blue Threshold", 0xAB0, TYPE_FLOAT },
	{ "Red Threshold", 0xAB4, TYPE_FLOAT },
	{ "Green Threshold", 0xAB8, TYPE_FLOAT },
	{ "Blue Threshold", 0xABC, TYPE_FLOAT },
	{ "Red Threshold", 0xAC0, TYPE_FLOAT },
	{ "Green Threshold", 0xAC4, TYPE_FLOAT },
	{ "Blue Threshold", 0xAC8, TYPE_FLOAT },
	{ "Red Threshold", 0xACC, TYPE_FLOAT },
	{ "Green Threshold", 0xAD0, TYPE_FLOAT },
	{ "Blue Threshold", 0xAD4, TYPE_FLOAT },
	{ "Red Threshold", 0xAD8, TYPE_FLOAT },
	{ "Green Threshold", 0xADC, TYPE_FLOAT },
	{ "Blue Threshold", 0xAE0, TYPE_FLOAT },
	{ "Red Threshold", 0xAE4, TYPE_FLOAT },
	{ "Green Threshold", 0xAE8, TYPE_FLOAT },
	{ "Blue Threshold", 0xAEC, TYPE_FLOAT },
	{ "Red Threshold", 0xAF0, TYPE_FLOAT },
	{ "Green Threshold", 0xAF4, TYPE_FLOAT },
	{ "Blue Threshold", 0xAF8, TYPE_FLOAT },
	{ "Red Threshold", 0xAFC, TYPE_FLOAT },
	{ "Green Threshold", 0xB00, TYPE_FLOAT },
	{ "Blue Threshold", 0xB04, TYPE_FLOAT },
	{ "Red Threshold", 0xB08, TYPE_FLOAT },
	{ "Green Threshold", 0xB0C, TYPE_FLOAT },
	{ "Blue Threshold", 0xB10, TYPE_FLOAT },
	{ "Red Threshold", 0xB14, TYPE_FLOAT },
	{ "Green Threshold", 0xB18, TYPE_FLOAT },
	{ "Blue Threshold", 0xB1C, TYPE_FLOAT },
	{ "Red Threshold", 0xB20, TYPE_FLOAT },
	{ "Green Threshold", 0xB24, TYPE_FLOAT },
	{ "Blue Threshold", 0xB28, TYPE_FLOAT },
	{ "Red Threshold", 0xB2C, TYPE_FLOAT },
	{ "Green Threshold", 0xB30, TYPE_FLOAT },
	{ "Blue Threshold", 0xB34, TYPE_FLOAT },
	{ "Red Threshold", 0xB38, TYPE_FLOAT },
	{ "Green Threshold", 0xB3C, TYPE_FLOAT },
	{ "Blue Threshold", 0xB40, TYPE_FLOAT },
	{ "Red Threshold", 0xB44, TYPE_FLOAT },
	{ "Green Threshold", 0xB48, TYPE_FLOAT },
	{ "Blue Threshold", 0xB4C, TYPE_FLOAT },
	{ "Red Threshold", 0xB50, TYPE_FLOAT },
	{ "Green Threshold", 0xB54, TYPE_FLOAT },
	{ "Blue Threshold", 0xB58, TYPE_FLOAT },
	{ "Red Threshold", 0xB5C, TYPE_FLOAT },
	{ "Green Threshold", 0xB60, TYPE_FLOAT },
	{ "Blue Threshold", 0xB64, TYPE_FLOAT },
	{ "Red Threshold", 0xB68, TYPE_FLOAT },
	{ "Green Threshold", 0xB6C, TYPE_FLOAT },
	{ "Blue Threshold", 0xB70, TYPE_FLOAT },
	{ "Red Threshold", 0xB74, TYPE_FLOAT },
	{ "Green Threshold", 0xB78, TYPE_FLOAT },
	{ "Blue Threshold", 0xB7C, TYPE_FLOAT },
	{ "Red Threshold", 0xB80, TYPE_FLOAT },
	{ "Green Threshold", 0xB84, TYPE_FLOAT },
	{ "Blue Threshold", 0xB88, TYPE_FLOAT }
};